<a href="https://colab.research.google.com/github/ArthurCBx/Introduction_to_Data_Science_Coursera/blob/main/Foundamentals_of_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']


In [ ]:
for person in people:
  x = lambda person : (person.split()[0] + ' ' + person.split()[-1])
  print(x(person))

Dr. Brooks
Dr. Collins-Thompson
Dr. Vydiswaran
Dr. Romero


In [ ]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

In [ ]:
answer = [(a + b + c + d) for a in lowercase for b in lowercase for c in digits for d in digits if a!=b and c != d]
answer[:15]

['ab01',
 'ab02',
 'ab03',
 'ab04',
 'ab05',
 'ab06',
 'ab07',
 'ab08',
 'ab09',
 'ab10',
 'ab12',
 'ab13',
 'ab14',
 'ab15',
 'ab16']

In [ ]:
import numpy as np
import math


## Array Creation

In [ ]:
a = np.array([1,2,3])
print(a)
print(a.ndim)
print(a.dtype)

[1 2 3]
1
int64


In [ ]:
np.random.rand(2,3)

array([[0.65926206, 0.60028263, 0.90399134],
       [0.59091228, 0.60077082, 0.92722939]])

In [ ]:
f = np.arange(10,50,3)
f

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [ ]:
np.linspace(0,2,20) # Start value, end value, number of values in the interval

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

## Array Operations

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

c = a-b
print(c)

d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [ ]:
farenheit = np.array([0,-10,-5,-15,0])

celcius = (farenheit - 31) * (5/9)
print(celcius)
print(celcius > -20)

[-17.22222222 -22.77777778 -20.         -25.55555556 -17.22222222]
[ True False False False  True]


In [ ]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print(A*B) # Element-wise
print('\n')
print(A@B) # Matrix multplication

[[2 0]
 [0 4]]


[[5 4]
 [3 4]]


In [ ]:
print(B.sum())
print(B.max())
print(B.min())
print(B.mean())

9
4
0
2.25


In [ ]:
a = np.arange(1,16,1)
b = np.arange(1,16,1).reshape(3,5)
a, b

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]))

In [ ]:
from PIL import Image
from IPython.display import display

array = np.random.rand(224,224,3)*255
array = array.astype(np.uint8)
display(Image.fromarray(array))

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
a[1,1]

[[1 2]
 [3 4]
 [5 6]]


np.int64(4)

In [ ]:
np.array([a[0,0],a[1,1],a[2,1]])

array([1, 4, 6])

In [ ]:
print(a[[0,1,2], [0,1,1]])

[1 4 6]


In [ ]:
print(a>5)
print(a[a>5])

[[False False]
 [False False]
 [False  True]]
[6]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[:2]) # gets the first two lines
print(a[:2, 1:3]) # first two lines but only the 2nd and 3rd element
print(a[a>6])

[[1 2 3 4]
 [5 6 7 8]]
[[2 3]
 [6 7]]
[ 7  8  9 10 11 12]


In [ ]:
sub_array = a[:2, 1:3]
print("sub array index [0,0] value before change:", sub_array[0,0])
sub_array[0,0] = 50
print("sub array index [0,0] value after change:", sub_array[0,0])
print("original array index [0,1] value after change:", a[0,1])

sub array index [0,0] value before change: 2
sub array index [0,0] value after change: 50
original array index [0,1] value after change: 50


# Regex

See more at - https://docs.python.org/3/library/re.html#re.sub

In [ ]:
import re
# re is the module where python stores regular expressions libraries

In [ ]:
text = "This is a good day"

if re.search("good", text):
  print("Wonderful!")
else:
  print("Alas :(")

Wonderful!


In [ ]:
text = "Amy works diligently. Amy gets good grades. Our sutednt Amy is successful."
re.split("Amy", text) # Creates a list of substrings


['',
 ' works diligently. ',
 ' gets good grades. Our sutednt ',
 ' is successful.']

In [ ]:
re.findall("Amy", text) # Look for a pattern and pull out all occurences


['Amy', 'Amy', 'Amy']

## Rules of regex processing
1. The character ^ means start and $ menas end.

2. The character '^' before a string means that the texte regex processor retrieves must start with the string you specify.

3. If you put the $ after the string, it means that the text regex retrieves must end with the string you specify


In [ ]:
re.search("^Amy", text) # returns a re.Match object

<re.Match object; span=(0, 3), match='Amy'>

## Patterns and Character Classes

In [ ]:
grades="ACAAAABCBCBAA"

print(re.findall("B", grades)) # Return the occurences of B in grades
print(re.findall("AB", grades)) # Return A followed by B
print(re.findall("[AB]", grades)) # Return the occurences of A's and B's, but not necesseraly one followed by the other

['B', 'B', 'B']
['AB']
['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A']


In [ ]:
re.findall("[A][B-C]", grades) # Instances where student receive an A followed by a B or C

['AC', 'AB']

[AB] pattern describes a set of possible characters which could be either (A OR B), while the [A][B-C] pattern denoted two sets of characters which must have been matched back to back.

In [ ]:
re.findall("AB|AC",grades)

['AC', 'AB']

In [ ]:
re.findall("[^A]", grades) # Return the occurences of patterns different of whats after the character ^, because it's written inside the brackets

['C', 'B', 'C', 'B', 'C', 'B']

In [ ]:
re.findall("^[^A]", grades) # As it wants to match any value at the beginning of the string which value is not an A, it returns an empty list

[]

In [ ]:
re.findall("^AC$", grades)

[]

## Quantifiers
Quantifiers are the number of times you want a pattern to be matched in order to match. The most basic is expressed as e{m,n} where e is the expression we are matching, m is the minimun number of times you want it to be matched and n is the maximum number of times the item could be matched.

In [ ]:
# Example. How many times has this student grades been on a back-to-back A's streak
re.findall("A{2,10}", grades) # Minimum of 2 A's in a row and max of 10 (just so it's big enough)

['AAAA', 'AA']

In [ ]:
re.findall("A{1,1}A{1,1}", grades)

['AA', 'AA', 'AA']

In [ ]:
# Using this, we could find a decreasing trend in a student's grades
re.findall("A{1,10}B{1,10}C{1,10}", grades)

['AAAABC']

> \w is a metacharacter that indicates all characters from a-zA-Z

> \s matches any whitespace character

>'*' means to match 0 or more times

In [ ]:
!wget -O ferpa.txt https://raw.githubusercontent.com/ArthurCBx/Introduction_to_Data_Science_Coursera/refs/heads/main/ferpa.txt?token=GHSAT0AAAAAADGFPWLYYK2M67UHK7MWTN7S2EGUQPQ

--2025-07-27 21:11:51--  https://raw.githubusercontent.com/ArthurCBx/Introduction_to_Data_Science_Coursera/refs/heads/main/ferpa.txt?token=GHSAT0AAAAAADGFPWLYYK2M67UHK7MWTN7S2EGUQPQ
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4245 (4.1K) [text/plain]
Saving to: ‘ferpa.txt’

ferpa.txt           100%[===================>]   4.15K  --.-KB/s    in 0s      

2025-07-27 21:11:51 (25.3 MB/s) - ‘ferpa.txt’ saved [4245/4245]



In [ ]:
with open("ferpa.txt","r") as file:
    # we'll read that into a variable called wiki
    wiki=file.read()
wiki

'Overview[edit]\nFERPA gives parents access to their child\'s education records, an opportunity to seek to have the records amended, and some control over the disclosure of information from the records. With several exceptions, schools must have a student\'s consent prior to the disclosure of education records after that student is 18 years old. The law applies only to educational agencies and institutions that receive funds under a program administered by the U.S. Department of Education.\n\nOther regulations under this act, effective starting January 3, 2012, allow for greater disclosures of personal and directory student identifying information and regulate student IDs and e-mail addresses.[2] For example, schools may provide external companies with a student\'s personally identifiable information without the student\'s consent.[2]\n\nExamples of situations affected by FERPA include school employees divulging information to anyone other than the student about the student\'s grades o

In [ ]:
titles = re.findall("[\w ]*\[edit\]",wiki)
titles

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [ ]:
for title in titles:
  print(re.split("[\[]",title)[0])

Overview
Access to public records
Student medical records


## Groups
Regex is a single pattern which is matched. But you can actually match different patterns(groups) at the same time and the refer to the groups you want.

To group patterns you use parentheses

In [ ]:
re.findall("([\w ]*)(\[edit\])",wiki)

[('Overview', '[edit]'),
 ('Access to public records', '[edit]'),
 ('Student medical records', '[edit]')]

In [ ]:
# Now, how do we get back a list of match objects? Function finditer()
for item in re.finditer("([\w ]*)(\[edit\])", wiki):
  print(item.groups())

('Overview', '[edit]')
('Access to public records', '[edit]')
('Student medical records', '[edit]')


In [ ]:
for item in re.finditer("([\w ]*)(\[edit\])", wiki):
  print(item.group(0))
  print(item.group(1))

Overview[edit]
Overview
Access to public records[edit]
Access to public records
Student medical records[edit]
Student medical records


In [ ]:
# You can also label the groups and look at the results as a dictionary
# The syntax is (?P<name>), ehere the parentheses starts the group, the ?P indicates that is
# an extension to basic regexes and <name> is the dictionary key we want to use wrapped in <>

for item in re.finditer("(?P<title>[\w ]*)(?P<edit_link>\[edit\])",wiki):
  print(item.groupdict()['title'])

Overview
Access to public records
Student medical records


In [ ]:
print(item.groupdict())

{'title': 'Student medical records', 'edit_link': '[edit]'}


## Quantifiers

Quantifiers, such as *, ? or m{n} can describe patterns

## Look-ahead and Look-behind
In this case, the
pattern being given to the regex engine is for text either before or after the text we are trying to isolate. For example, in our headers we want to isolate text which  comes before the [edit] rendering, but
we actually don't care about the [edit] text itself. Thus far we have been throwing the [edit] away, but if we want to use them to match but don't want to capture them we could put them in a group and use look ahead
instead with ?= syntax

In [ ]:
for item in re.finditer("(?P<title>[\w ]+)(?=\[edit\])", wiki):
  # We are matching two groups. The first named title and will have any amount of whitespace
  # or regular characters, the second will be the characters [edit] but we don't actually want this
  # edit put in our output match objects

  print(item)

<re.Match object; span=(0, 8), match='Overview'>
<re.Match object; span=(2715, 2739), match='Access to public records'>
<re.Match object; span=(3692, 3715), match='Student medical records'>


## Example

In [ ]:
!wget -O buddhist.txt https://raw.githubusercontent.com/ArthurCBx/Introduction_to_Data_Science_Coursera/refs/heads/main/buddhist.txt?token=GHSAT0AAAAAADGFPWLZM74T656ALWE6L2JS2EGUZ3A

--2025-07-27 21:21:52--  https://raw.githubusercontent.com/ArthurCBx/Introduction_to_Data_Science_Coursera/refs/heads/main/buddhist.txt?token=GHSAT0AAAAAADGFPWLZM74T656ALWE6L2JS2EGUZ3A
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1816 (1.8K) [text/plain]
Saving to: ‘buddhist.txt’

buddhist.txt        100%[===================>]   1.77K  --.-KB/s    in 0s      

2025-07-27 21:21:52 (10.0 MB/s) - ‘buddhist.txt’ saved [1816/1816]



In [ ]:
with open("buddhist.txt", "r") as file:
  wiki_example = file.read()
wiki_example

'Buddhist universities and colleges in the United States\nFrom Wikipedia, the free encyclopedia\nJump to navigationJump to search\n\nThis article needs additional citations for verification. Please help improve this article by adding citations to reliable sources. Unsourced material may be challenged and removed.\nFind sources: "Buddhist universities and colleges in the United States" – news · newspapers · books · scholar · JSTOR (December 2009) (Learn how and when to remove this template message)\nThere are several Buddhist universities in the United States. Some of these have existed for decades and are accredited. Others are relatively new and are either in the process of being accredited or else have no formal accreditation. The list includes:\n\nDhammakaya Open University – located in Azusa, California, part of the Thai Wat Phra Dhammakaya[1]\nDharmakirti College – located in Tucson, Arizona Now called Awam Tibetan Buddhist Institute (http://awaminstitute.org/)\nDharma Realm Buddh

In [ ]:
# Triple '#' just means a long line
pattern = """
(?P<title>.*)       #The university title .* just means any number of characters
(–\ located\ in\ )  #An indicator of the location
(?P<city>\w*)       #City the university is in
(,\ )               #Separator for the state
(?P<state>\w*)      #The state the city is located in"""

for item in re.finditer(pattern, wiki_example,re.VERBOSE):
  print(item.groupdict())

{'title': 'Dhammakaya Open University ', 'city': 'Azusa', 'state': 'California'}
{'title': 'Dharmakirti College ', 'city': 'Tucson', 'state': 'Arizona'}
{'title': 'Dharma Realm Buddhist University ', 'city': 'Ukiah', 'state': 'California'}
{'title': 'Ewam Buddhist Institute ', 'city': 'Arlee', 'state': 'Montana'}
{'title': 'Institute of Buddhist Studies ', 'city': 'Berkeley', 'state': 'California'}
{'title': 'Maitripa College ', 'city': 'Portland', 'state': 'Oregon'}
{'title': 'University of the West ', 'city': 'Rosemead', 'state': 'California'}
{'title': 'Won Institute of Graduate Studies ', 'city': 'Glenside', 'state': 'Pennsylvania'}


# Exercises

In [ ]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [ ]:
import numpy as np
a = np.random.rand(20,20)
b = np.random.rand(20,20)

def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result
print(l2_dist(a,b))
print(l2_dist(a.T,b.T))
print(np.reshape(a,(20*20)),np.reshape(b,(20*20,1)))

8.424330697549857
8.424330697549857
[0.05538348 0.12855102 0.3527698  0.93123196 0.46789941 0.12698667
 0.23807778 0.1327147  0.13667015 0.7171913  0.88487109 0.74806276
 0.74769813 0.12988202 0.37898158 0.60417448 0.88180819 0.03840758
 0.6386384  0.90488911 0.02758265 0.89182241 0.09354865 0.4107171
 0.93731296 0.20548761 0.64156024 0.70902678 0.35644851 0.65922388
 0.539173   0.56352143 0.52761941 0.06512931 0.42053551 0.47055203
 0.15861796 0.86146796 0.84481753 0.83836851 0.85369672 0.46639827
 0.59007444 0.32842618 0.17525262 0.97415487 0.32598593 0.93008832
 0.92282886 0.2257456  0.13339204 0.66604969 0.53848404 0.79313421
 0.45522911 0.35854987 0.18304439 0.46019387 0.12806318 0.01192842
 0.87714923 0.67367291 0.92093762 0.72422393 0.15678462 0.45716836
 0.01954224 0.82500392 0.03691641 0.07831006 0.27549686 0.10187429
 0.69826366 0.45944762 0.33505721 0.23746181 0.61651388 0.5782208
 0.19673553 0.76081651 0.01800123 0.53080481 0.39230919 0.79009751
 0.79022699 0.27830216 0.286

In [ ]:
a1 = np.random.rand(4)
a2 = np.random.rand(4,1)
a4 = np.arange(1,4,1)
a4.ndim

1

In [ ]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [ ]:
s = 'ACBCAC'
re.findall('^AC',s)

['AC']

In [ ]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
L

5

In [ ]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = '\(.\)'
print(len(re.findall(pattern,text)))

4


In [ ]:
import re
def names():
    simple_string = """Amy is 5 years old, and her sister Mary is 2 years old.
    Ruth and Peter, their parents, have 3 kids."""

    pattern = "[A-Z]\w+"
    return re.findall(pattern,simple_string)
names()

['Amy', 'Mary', 'Ruth', 'Peter']

In [ ]:
import re
def grades():
    with open ("assets/grades.txt", "r") as file:
        grades = file.read()

    pattern = "(?P<name>[A-Z].*):\sB"
    names=[]
    for person in re.finditer(pattern,grades):
        names.append(person.groupdict()['name'])
    return names

names = grades()
len(names)

16

In [ ]:
import re
def logs():
    with open("assets/logdata.txt", "r") as file:
        logdata = file.read()
    pattern = """
   (?P<host>\d+\.\d+\.\d+\.\d+)
   (\s[-]\s)
   (?P<user_name>\w+|[-]+)
   (\s\[)
   (?P<time>\d+\/\w+\/\d+:\d+:\d+:\d+\s-\d+)
   (\]\s")
   (?P<request>.*)
   (".*)
   """
    result = []
    for item in re.finditer(pattern, logdata, re.VERBOSE):
        result.append(item.groupdict())
    return result

result = logs()
result

[{'host': '146.204.224.152',
  'user_name': 'feest6811',
  'time': '21/Jun/2019:15:45:24 -0700',
  'request': 'POST /incentivize HTTP/1.1'},
 {'host': '197.109.77.178',
  'user_name': 'kertzmann3129',
  'time': '21/Jun/2019:15:45:25 -0700',
  'request': 'DELETE /virtual/solutions/target/web+services HTTP/2.0'},
 {'host': '156.127.178.177',
  'user_name': 'okuneva5222',
  'time': '21/Jun/2019:15:45:27 -0700',
  'request': 'DELETE /interactive/transparent/niches/revolutionize HTTP/1.1'},
 {'host': '100.32.205.59',
  'user_name': 'ortiz8891',
  'time': '21/Jun/2019:15:45:28 -0700',
  'request': 'PATCH /architectures HTTP/1.0'},
 {'host': '168.95.156.240',
  'user_name': 'stark2413',
  'time': '21/Jun/2019:15:45:31 -0700',
  'request': 'GET /engage HTTP/2.0'},
 {'host': '71.172.239.195',
  'user_name': 'dooley1853',
  'time': '21/Jun/2019:15:45:32 -0700',
  'request': 'PUT /cutting-edge HTTP/2.0'},
 {'host': '180.95.121.94',
  'user_name': 'mohr6893',
  'time': '21/Jun/2019:15:45:34 -0700'

In [ ]:
one_item={'host': '146.204.224.152',
  'user_name': 'feest6811',
  'time': '21/Jun/2019:15:45:24 -0700',
  'request': 'POST /incentivize HTTP/1.1'}
one_item in logs(), "Sorry, this item should be in the log results, check your formating"


(True, 'Sorry, this item should be in the log results, check your formating')